# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

jobs:
- job:
  displayName: 'Build Sample App'
  steps:
  - bash: 'cd iOS/SampleApp/ && pod install'
    displayName: 'Install dependencies'
  - task: Xcode@5
    displayName: 'Build archive for QuickAuthSample'
    inputs:
      actions: 'archive'
      scheme: 'SampleAppiOS'
      sdk: 'iphoneos'
      configuration: 'Release'
      xcWorkspacePath: 'iOS/SampleApp/QuickAuthSample.xcworkspace'
      xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath
      packageApp: true
      archivePath: 'iOS/SampleApp/archieve'
      exportPath: 'iOS/SampleApp/ipa'
      signingOption: nosign

  - task: CopyFiles@2
    displayName: 'Copy Archieves to Staging Directory'
    inputs:
      SourceFolder: 'iOS/SampleApp/ipa'
      Contents: '*.ipa'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@1
    name: PublishPipelineArtifact1
    displayName: 'Publish Artifact'
    inputs:
      ArtifactName: BuildOutputs
      TargetPath: $(Build.ArtifactStagingDirectory)

  - task: EsrpCodeSigning@2
    inputs:
      ConnectedServiceName: 'QuickAuthCodeSignConnection'
      FolderPath: '$(Build.ArtifactStagingDirectory)'
      Pattern: '*.ipa'
      signConfigType: 'inlineSignParams'
      inlineOperation: |
        [
                {
                    "KeyCode" : "CP-231522",
                    "OperationCode" : "SigntoolSign",
                    "Parameters" : {
                        "OpusName" : "Microsoft",
                        "OpusInfo" : "http://www.microsoft.com",
                        "Append" : "/as",
                        "FileDigest" : "/fd \"SHA256\"",
                        "PageHash" : "/NPH",
                        "TimeStamp" : "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                    },
                    "ToolName" : "sign",
                    "ToolVersion" : "1.0"
                },
                {
                    "KeyCode" : "CP-231522",
                    "OperationCode" : "SigntoolVerify",
                    "Parameters" : {},
                    "ToolName" : "sign",
                    "ToolVersion" : "1.0"
                }
            ]
      SessionTimeout: '60'
      MaxConcurrency: '50'
      MaxRetryAttempts: '5'